### ISSUE TITLE
Alert component title gets cut off

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#116]
hey all,

when importing this `Alert` component, the Title box doesn't grow with the text so if the text gets longer, it gets cut off:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/596793a1-ece8-4eae-8a94-dfbe7c89b784)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/v87ftBRPngy3xXKuCpZP/yla3aa1yn3ahj

**Comment by alexandergrot** [comment]
same is true for the content text, if this grows the outer container doesn't grow with it so it gets cut off

**Comment by gqio** [comment]
Hello @alexandergrot

For full width element you need to specify a viewport.
You can access this in the edit component window
![image](https://github.com/divriots/story-to-design/assets/1063530/5e4a48db-b584-41d2-8f5a-395ac171f3b1)

Hope this helps.

Best

**Comment by alexandergrot** [comment]
hey @gqio , 
good point, changing this kind of gives me a new problem, if the content text is really short the title gets also cut off. it looks like it is dependant on the length of the content text because if i put in a longer content text the title doesn't get cut off:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/418c4d6f-ea93-4e0d-b411-0caa30d78da9)

should i open a new issue for this? or can you work on this with this issue?

thanks so far

**Comment by gqio** [comment]
Hello @alexandergrot 

I released a fix for this could you please check with the new plugin ?
should be version `9585c0c4921da1a0a5f5206a1e18c5d639e5fee6`

Best

**Comment by alexandergrot** [comment]
sadly this isn't fixed for me and a colleague when we tested it.
![grafik](https://github.com/divriots/story-to-design/assets/102791744/70e43847-e098-41aa-aca6-66cbdbcae9ee)
![grafik](https://github.com/divriots/story-to-design/assets/102791744/ad17037c-29c5-47fc-8394-785cb72cda03)

and also the close button (x) on the right side doesn't move when the outer container is resized. if i remember correctly, this was fixed once but now seems to be an issue again

**Comment by gqio** [comment]
Hello @alexandergrot 

I am looking into it

Best

**Comment by gqio** [comment]
Hello @alexandergrot 

Regarding the text

![image](https://github.com/divriots/story-to-design/assets/1063530/c24abd53-0d51-4e29-8e65-70e25abaad27)

There is a -2px margin here.
This leads us to introducing a margin wrapper, but since there is no concept of negative margin/padding in Figma we end with using absolute positionning. And this is breaking the autolayout cascade. Without this negative margin we won't introduce this margin wrapper and it will behave correctly. We can't do pretty much here since it's not supported in Figma.

![image](https://github.com/divriots/story-to-design/assets/1063530/4e0a69d4-0f79-4ca3-936c-11ace65a6e7e)

What do you expect from the perspective of the plugin here ? Or maybe we can handle this in different way, do you have some recommandation on how you would do that ?

Now I will dig into the issue of the close icon.

Best
