### ISSUE TITLE
Visual Review broken

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#123]
## Describe the problem ##
A few of our components (including this Table) have updates to be reviewed. 
It is not possible though to review the changes visuallly for any of the components. This is the error message:
<img width="448" alt="visual-review-broken" src="https://github.com/divriots/story-to-design/assets/129752452/b2647ab4-0d76-4ebd-b2c8-bfbe3ebee0b6">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/fnG4s1wx0tN9ByiAL0Nr/1xrsf6cs5lu7t

**Comment by elenabraeutigam** [comment]
After trying to just update those components (even though I couldn't first see the preview of the changes), I just realised that this does not work either. 

<img width="363" alt="Screenshot 2023-11-03 at 14 26 18" src="https://github.com/divriots/story-to-design/assets/129752452/60b4bbae-1f5f-4679-b875-7be346d63a73">

After clicking "Update 8 variants" I'm being redirected to the list, but the component in the Figma canvas did not change and the "Review and Update" button is still there...
<img width="440" alt="Screenshot 2023-11-03 at 14 26 08" src="https://github.com/divriots/story-to-design/assets/129752452/09fdab0c-f1ae-4ca9-825e-9fc849b1e945">

**Comment by muryoh** [comment]
Hi @elenabraeutigam , sorry about that

I believe it may be caused by an issue we've identified and fixed internally
We'll try to release a fix for it asap

**Comment by muryoh** [comment]
Hi @elenabraeutigam,

We just released a fix for it, you'll need to update the agent :pray: 

Cheers
Remy

**Comment by elenabraeutigam** [comment]
@muryoh Unfortunately, the new release didn't fix the issue.
Restarting Figma, the agent, etc again also didn't help.

**Comment by muryoh** [comment]
That's unexpected
Would you mind trying to reprocess that component?

![image](https://github.com/divriots/story-to-design/assets/1789748/a2718734-a575-4da0-9d52-5672e94d68a6)

**Comment by elenabraeutigam** [comment]
That works! Thank you 🙏

**Comment by muryoh** [comment]
Great news!
Sorry about the manual step - in some cases it is hard for us to detect this

Cheers
Remy
