### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by felipemoslavacz** [divriots/story-to-design#152]
## Describe the problem ##

Missing the image on all variants and the title is cut off on mobile.

---
Bug report identity: Please do not edit

Task path: iy5LAnxjYjDyTYLu2Haf/nqkzW9yDN8IslZC7Hz6M/1odk8s01qtqy9h

**Comment by muryoh** [comment]
Hi @felipemoslavacz , thanks for the report!

Issue identified, fix will be coming up soon

Cheers
Remy

**Comment by muryoh** [comment]
Hi there, we released a new version of the `agent` that fixes this

Please upgrade to at least v1.20.7 to benefit from it (restarting the agent should prompt for an upgrade)

Cheers,
Remy

**Comment by felipemoslavacz** [comment]
@muryoh Thanks for responding, this was the only issue that wasn't fixed after triggering the reprocessing story.

The images work now, but the title is still cut off on mobile:

<img width="457" alt="image" src="https://github.com/divriots/story-to-design/assets/3967526/8510f64d-3bbb-4fa5-ab32-9b7d3b73b333">

**Comment by muryoh** [comment]
It seems to have been fixed with the last releases, as I'm getting this:

![image](https://github.com/divriots/story-to-design/assets/1789748/3479f83b-3d06-4c33-bca6-3993ac009ee4)

Closing as resolved, don't hesitate to reopen if needed!

Cheers,
Remy
