### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by jessiehuang-maker** [divriots/story-to-design#234]
## Describe the problem ##

Hi, I'm experiencing issues while importing the modal. I used a CSS selector to import the modal.

- Our Modal has a responsive design for mobile. But after importing, if you remove the modal, it doesn't have a responsive action.
- The modal content background disappeared
- The content doesn't extend when the designer is trying to add a button or when the text is too long
- The modal border radius is not right

---
Bug report identity: Please do not edit

Task path: QVtgEiXXJMJkMxTjSetw/5SF5JK2XawcG25l55ccw/1vbk0q01ls2i6e

**Comment by muryoh** [comment]
Hi @jessiehuang-maker ,

Sorry for the late feedback on that one 🙏 
It's possible so of the issues have been fixed which would explain why I cannot see some of your problems!

> Our Modal has a responsive design for mobile. But after importing, if you remove the modal, it doesn't have a responsive action.

I'm sorry I did not get it :(

> The modal content background disappeared

Indeed, will check!

> The content doesn't extend when the designer is trying to add a button or when the text is too long

This is what I'm seeing:

<img width="556" height="763" alt="Image" src="https://github.com/user-attachments/assets/1ce043a4-f470-45d1-bb49-56bf27f15db7" />

Is it not expected?

It seems to be very similar in the browser:

<img width="1235" height="1005" alt="Image" src="https://github.com/user-attachments/assets/a73fd031-f16c-4c28-ad6a-b54fb3d0c19f" />

> The modal border radius is not right

It seems ok for me, I see 16px in Figma and in the storybook?

<img width="986" height="218" alt="Image" src="https://github.com/user-attachments/assets/0620b789-e2f9-49b8-873a-a57ec7d80f64" />

<img width="345" height="100" alt="Image" src="https://github.com/user-attachments/assets/29242265-d898-4a0f-940f-9d0b620c2890" />

Cheers,
Remy

**Comment by muryoh** [comment]
After having a first look, I have some feedback regarding the configuration:
- since you only seem interested in getting the Modal itself, I would only capture the story with `open=true`, not both

<img width="533" height="531" alt="Image" src="https://github.com/user-attachments/assets/934e3d16-5e5a-49c6-af5d-08d2b921c2d4" />

- the selector you used only captures the modal content but not the overlay, I would change it to `.MuiModal-root`

<img width="578" height="193" alt="Image" src="https://github.com/user-attachments/assets/7b7117ee-66f8-4814-ab2f-6767de76295d" />

I did notice that the overlay effective "z-index" in Figma is wrong, as it is rendered above the Modal. I've pushed a fix for it internally!

**Comment by muryoh** [comment]
Hi @jessiehuang-maker , sorry for the late feedback but this has been fixed 
You should be able to get it after updating the agent and reprocessing the component 👍

**Comment by jessiehuang-maker** [comment]
Hi Thanks, I was going to try it after button & icons fixed. I will do it now and check back after button & icon issues. Thanks

**Comment by jessiehuang-maker** [comment]
@muryoh My container still can't extend and it only has one button in the sub component. Not sure why looks so different from yours 

Task path: QVtgEiXXJMJkMxTjSetw/E3UoiT5dNEKufeByiul4/pzbdg6551r9z

<img width="1031" height="734" alt="Image" src="https://github.com/user-attachments/assets/c138241b-1687-4793-aafd-580a2fca4221" />
