### ISSUE TITLE
material-ui/RadioButton missing padding in disabled state

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#84]
when importing a story where a single  [material-ui/RadioButton](https://mui.com/material-ui/react-radio-button/) is used, the padding gets lost when the disabled state is chosen.

component with normal and disabled state in storybook: 
![grafik](https://github.com/divriots/story-to-design/assets/102791744/e97bddce-c9db-4e15-a591-a5395a323d6e)
![grafik](https://github.com/divriots/story-to-design/assets/102791744/f4074758-9988-492e-a823-6743b90ec6b3)

component with normal and disabled state in figma:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/26dc0373-cdb0-4f80-8c5d-10abc028ec03)
![grafik](https://github.com/divriots/story-to-design/assets/102791744/c1d13ab3-aba0-47b4-8bcb-fef887c6c2b7)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/1hykc06p3ov1k

**Comment by gqio** [comment]
Hello @alexandergrot 

Fix has been deployed with the latest release.
You will need to `Reprocess` the story (to get the new model) and `Reset` the canvas (to get the new component in Figma) with the new plugin version

Best.

**Comment by alexandergrot** [comment]
hey @gqio, 

i can still reproduce the original reported problem. see this screenshot:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/59c0c070-b519-4fd1-b10d-81b166704dcf)

i restarted figma and ran the plugin again, reprocessed the story and reset the canvas but the problem persists. should i create another issue with the `Report a problem`  function or do you want to reopen this issue?

**Comment by gqio** [comment]
Hello @alexandergrot 

Apparently we missed a fix in the release.

![image](https://github.com/divriots/story-to-design/assets/1063530/933a09ec-909e-4710-9487-3b6969864464)

Should be fine now with the latest release with the new Story.to.design Agent and the new Figma Plugin

Best.
