### ISSUE TITLE
[Component Issue Report] Text boxes not adjusting to long content & Resizing components behaving oddly

### ISSUE THREAD

**Issue by chungsi** [divriots/story-to-design#91]
### A) Text boxes not adjusting to long content
When importing this component (and other similar components in this project), editing the text to be longer than the initial text box will result in text overflowing the container.
![image](https://github.com/divriots/story-to-design/assets/14225300/ec38f0c9-da10-4937-8d19-0fb0a4032dcc)

It seems like all the text boxes have their horizontal sizing to be "hug" when it should be "fixed width" (card title, text in the top-left flag), and vice versa (the "offer ends" banner below image).

### B) Resizing components behaving oddly
Also, when resizing this component, the elements don't stretch like it would in code. It seems like the weak link is the image that's not resizing its height so that Figma's auto layout can do its magic:
![image](https://github.com/divriots/story-to-design/assets/14225300/dc90785b-bffc-4514-966c-ef115aa40b4f)

Please let me know if there's anything I would need to change in the CSS/HTML to better support the imports!

---
Bug report identity: Please do not edit

Task path: R702fkgNoAQvwSdKueSF/rmWmGXWJ9yBB8BdZUECm/l7ebw2jtcew4

**Comment by muryoh** [comment]
Hi @chungsi, duely received, we're doing our best to get a fix for it
Team size is greatly reduced at the moment (holidays), please bear with us 🙏

**Comment by muryoh** [comment]
Internally pushed a fix for the first issue
The second one is trickier to deal with

**Comment by muryoh** [comment]
We just released a fix for the first issue, we'll need to check what can be done for the second one!

Note that it may be tricky as my understing is Figma does not support keeping aspect ratio for layers. There are hacks that some people found, but they seem to be for some specific ratio values, I'm not sure there's a way to do that generically for everything

**Comment by chungsi** [comment]
Thank you!
I'm testing the changes for the first issue, and I'm not sure if I'm resetting stuff correctly because I'm still seeing overflow text.

I restarted Figma after the updates, reprocessed story, and reset canvas. Then I updated the component. I also imported a new instance of the component but it behaves the same as my screen shot.

**Working**
* Description text wraps and pushes container.
* The "Tile Message" & "Banner Text" at the top left of the component wraps the text.

**Not Quite Working?**
* The "Offer Ends" countdown text container still causes wrapping issues on import.
* Title text doesn't wrap.

Let me know if I'm missing something or if there's other steps I should try! Thank you!

![image](https://github.com/divriots/story-to-design/assets/14225300/83b5ac5e-fcb8-4193-a2e7-584246858aad)

**Comment by muryoh** [comment]
Hey, thanks for the feedback!

So... the answer is going to be a bit tricky
Do you have missing fonts like I do here on your end?

![image](https://github.com/divriots/story-to-design/assets/1789748/ebc8a7a0-5c15-4ff6-81bd-4cdf9d171f31)

The problem with missing the fonts in Figma is that we may not be able to size text elements properly, preventing us from also computing/applying autolayout properly

I imagine that's what we're seeing here, especially on the `Offer Ends` title as it seems to be using a web font that I dont have installed on my machine, `Trade Gothic Next LT Pro`.

**The best thing to do when having missing fonts** as indicated in the plugin is to install those fonts locally
Is it something you can do?

As for the `Results Card Title` - I'm wondering what's happening there. For me, locally, the font used in the browser is `Liberation Sans` because the font-family refers to `sans-serif` and that's the family I have locally (I'm on Linux)
What do you have on your end? Are you on Windows/MacOS?

![image](https://github.com/divriots/story-to-design/assets/1789748/f36d3161-e52c-4363-a3cf-d522cf21f2dc)

**Comment by chungsi** [comment]
Ah, I figured it might be related to the fonts! I'm in the middle of trying to get access to the fonts and then test the imports again. Will update you!

**Comment by gqio** [comment]
Hello @chungsi 

Please open a new issue if you still encounter the issue with fonts installed.

Best
