### ISSUE TITLE
Button width does not adjust when changing the button label

### ISSUE THREAD

**Issue by msfay9** [divriots/story-to-design#98]
Issue: the button width does not adjust when changing the button label. A manual change in Figma changing the horizontal resizing from "fixed" to "hug" fixes the issue. Things seem fine on the Storybook side, so wondering if this has to do with flexbox interpretation issues

From Remy on Discord
> Yep, very likely a bug that we need to fix. DOM layout is quite complex (especially the sheer number of combinations to support) and mapping to Figma makes it even more challenging. We're trying to fix the loopholes are they're pointed out to us!

---
Bug report identity: Please do not edit

Task path: VDHa3wgXzblKxeDCyHKM/d5QEm8gDImjAKEYKsGyc/1kqp0ql1ggg83z

**Comment by gqio** [comment]
Hello @msfay9 

We released a fix for this, could you please confirm when using the latest agent and last plugin it works for you ?
(just use the auto update agent and close and reopen the tab of your design file to force update the plugin)

Best

**Comment by msfay9** [comment]
Using the latest and have updated the components, still not working on my
end sadly


*Amplitude HQ*
631 Howard Street
San Francisco, CA 94105
*Meredith Fay*
Senior Product Designer
E: ***@***.***
M: (908) 246-6641
W: amplitude.com

**Comment by gqio** [comment]
Hello @msfay9 

Sorry I couldn't reproduce the issue with the latest plugin on my side and I assumed it was fixed.
I will check with @muryoh tomorrow if we can tackle this and fix your issue.

Do you have a particular variant where it's not working ? Or all of them are not working ?

Best

**Comment by gqio** [comment]
Hello @msfay9 

Could you please check and confirm it's working with the latest version of the plugin ? Release in progress should be available in 10 min-ish
Don't forget to reset on the canvas the component.

Best
